from models.title import Title


class TestTitle:
    def test_extract_eecid(self):
        ti = Title(language="en", value="Council Directive 88/610/EEC of 24 November 1988",
              celex_id="")
        assert ti.extract_eecid == "88/610/EEC"

    def test_ep_council_regulation(self):
        # http://data.europa.eu/eli/reg/2016/679/oj

        test_dict1 = {
            "bg": "Регламент (ЕС) 2016/679 на Европейския парламент и на Съвета от 27 април 2016 година относно защитата на физическите лица във връзка с обработването на лични данни и относно свободното движение на такива данни и за отмяна на Директива 95/46/ЕО (Общ регламент относно защитата на данните) (текст от значение за ЕИП)",
            "cs": "Nařízení (EU) 2016/679 Evropského parlamentu a Rady ze dne 27. dubna 2016 o ochraně fyzických osob v souvislosti se zpracováním osobních údajů a o volném pohybu těchto údajů a o zrušení směrnice 95/46/ES (obecné nařízení o ochraně osobních údajů) (Text s významem pro EHP)",
            "da": "Europa-Parlamentets og Rådets forordning (EU) 2016/679 af 27. april 2016 om beskyttelse af fysiske personer i forbindelse med behandling af personoplysninger og om fri udveksling af sådanne oplysninger og om ophævelse af direktiv 95/46/EF (generel forordning om databeskyttelse) (EØS-relevant tekst)",
            "de": "Verordnung (EU) 2016/679 des Europäischen Parlaments und des Rates vom 27. April 2016 zum Schutz natürlicher Personen bei der Verarbeitung personenbezogener Daten, zum freien Datenverkehr und zur Aufhebung der Richtlinie 95/46/EG (Datenschutz-Grundverordnung) (Text von Bedeutung für den EWR)",
            "el": "Κανονισμός (ΕΕ) 2016/679 του Ευρωπαϊκού Κοινοβουλίου και του Συμβουλίου της 27ης Απριλίου 2016 για την προστασία των φυσικών προσώπων έναντι της επεξεργασίας δεδομένων προσωπικού χαρακτήρα και για την ελεύθερη κυκλοφορία των δεδομένων αυτών και για την κατάργηση της οδηγίας 95/46/ΕΚ (Γενικός Κανονισμός για την Προστασία Δεδομένων) (Κείμενο που παρουσιάζει ενδιαφέρον για τον ΕΟΧ)",
            "en": "Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation) (Text with EEA relevance)",
            "es": "Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de 2016 relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos y por el que se deroga la Directiva 95/46/CE (Reglamento general de protección de datos) (Texto pertinente a efectos del EEE)",
            "et": "Euroopa Parlamendi ja nõukogu määrus (EL) 2016/679, 27. aprill 2016, füüsiliste isikute kaitse kohta isikuandmete töötlemisel ja selliste andmete vaba liikumise kohta ning millega tunnistatakse kehtetuks direktiiv 95/46/EÜ (isikuandmete kaitse üldmäärus) (EMPs kohaldatav tekst)",
            "fi": "Euroopan parlamentin ja neuvoston asetus (EU) 2016/679, annettu 27 päivänä huhtikuuta 2016, luonnollisten henkilöiden suojelusta henkilötietojen käsittelyssä sekä näiden tietojen vapaasta liikkuvuudesta ja direktiivin 95/46/EY kumoamisesta (yleinen tietosuoja-asetus) (ETA:n kannalta merkityksellinen teksti)",
            "fr": "Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016 relatif à la protection des personnes physiques à l'égard du traitement des données à caractère personnel et à la libre circulation de ces données et abrogeant la directive 95/46/CE (règlement général sur la protection des données) (Texte présentant de l'intérêt pour l'EEE)",
            "ga": "Rialachán (AE) 2016/679 ó Pharlaimint na hEorpa agus ón gComhairle an 27 Aibreán 2016 maidir le cosaint daoine nádúrtha i ndáil le próiseáil sonraí pearsanta agus maidir le saorghluaiseacht na sonraí sin, agus lena n-aisghairtear Treoir 95/46/CE (Rialachán Ginearálta maidir le Cosaint Sonraí) (Téacs atá ábhartha maidir leis an LEE)",
            "hr": "Uredba (EU) 2016/679 Europskog parlamenta i Vijeća od 27. travnja 2016. o zaštiti pojedinaca u vezi s obradom osobnih podataka i o slobodnom kretanju takvih podataka te o stavljanju izvan snage Direktive 95/46/EZ (Opća uredba o zaštiti podataka) (Tekst značajan za EGP)",
            "hu": "Az Európai Parlament és a Tanács (EU) 2016/679 rendelete (2016. április 27.) a természetes személyeknek a személyes adatok kezelése tekintetében történő védelméről és az ilyen adatok szabad áramlásáról, valamint a 95/46/EK irányelv hatályon kívül helyezéséről (általános adatvédelmi rendelet) (EGT-vonatkozású szöveg)",
            "it": "Regolamento (UE) 2016/679 del Parlamento europeo e del Consiglio del 27 aprile 2016 relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali, nonché alla libera circolazione di tali dati e che abroga la direttiva 95/46/CE (regolamento generale sulla protezione dei dati) (Testo rilevante ai fini del SEE)",
            "lt": "2016 m. balandžio 27 d. Europos Parlamento ir Tarybos reglamentas (ES) 2016/679 dėl fizinių asmenų apsaugos tvarkant asmens duomenis ir dėl laisvo tokių duomenų judėjimo ir panaikinantis Direktyvą 95/46/EB (Bendrasis duomenų apsaugos reglamentas) (Tekstas svarbus EEE)",
            "lv": "Eiropas Parlamenta un Padomes Regula (ES) 2016/679 (2016. gada 27. aprīlis) par fizisku personu aizsardzību attiecībā uz personas datu apstrādi un šādu datu brīvu apriti un ar ko atceļ Direktīvu 95/46/EK (Vispārīgā datu aizsardzības regula) (Dokuments attiecas uz EEZ)",
            "mt": "Regolament (UE) 2016/679 tal-Parlament Ewropew u tal-Kunsill tat-27 ta' April 2016 dwar il-protezzjoni ta' persuni fiżiċi fir-rigward tal-ipproċessar ta' data personali u dwar il-moviment liberu ta' tali data, u li jħassar id-Direttiva 95/46/KE (Regolament Ġenerali dwar il-Protezzjoni tad-Data) (Test b'rilevanza għaż-ŻEE)",
            "nl": "Verordening (EU) 2016/679 van het Europees Parlement en de Raad van 27 april 2016 betreffende de bescherming van natuurlijke personen in verband met de verwerking van persoonsgegevens en betreffende het vrije verkeer van die gegevens en tot intrekking van Richtlijn 95/46/EG (algemene verordening gegevensbescherming) (Tekst met EER-relevantie)",
            "pl": "Rozporządzenie Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylające dyrektywę 95/46/WE (ogólne rozporządzenie o ochronie danych) (Tekst mający znaczenie dla EOG)",
            "pt": "Regulamento (UE) 2016/679 do Parlamento Europeu e do Conselho de 27 de abril de 2016 relativo à proteção das pessoas singulares no que diz respeito ao tratamento de dados pessoais e à livre circulação desses dados e que revoga a Diretiva 95/46/CE (Regulamento Geral sobre a Proteção de Dados) (Texto relevante para o EEE)",
            "ro": "Regulamentul (UE) 2016/679 al Parlamentului European și al Consiliului din 27 aprilie 2016 privind protecția persoanelor fizice în ceea ce privește prelucrarea datelor cu caracter personal și privind libera circulație a acestor date și de abrogare a Directivei 95/46/CE (Regulamentul general privind protecția datelor) (Text cu relevanță pentru SEE)",
            "sk": "Nariadenie Európskeho parlamentu a Rady (EÚ) 2016/679 z 27. apríla 2016 o ochrane fyzických osôb pri spracúvaní osobných údajov a o voľnom pohybe takýchto údajov a o zrušení smernice 95/46/ES (všeobecné nariadenie o ochrane údajov) (Text s významom pre EHP)",
            "sl": "Uredba (EU) 2016/679 Evropskega parlamenta in Sveta z dne 27. aprila 2016 o varstvu posameznikov pri obdelavi osebnih podatkov in o prostem pretoku takih podatkov ter o razveljavitvi Direktive 95/46/ES (splošna uredba o varstvu podatkov) (Besedilo velja za EGP)",
            "sv": "Europaparlamentets och rådets förordning (EU) 2016/679 av den 27 april 2016 om skydd för fysiska personer med avseende på behandling av personuppgifter och om det fria flödet av sådana uppgifter och om upphävande av direktiv 95/46/EG (allmän dataskyddsförordning) (Text av betydelse för EES)",
        }
        for lang, title in test_dict1.items():
            title = Title(language=lang, value=title, celex_id="")
            print(f"{lang}: {title.shortname_without_institution}")
            assert title.shortname_without_institution is not None
            assert title.shortname_with_institution != ""


    def test_council_decision(self):
        # http://data.europa.eu/eli/dec_impl/2022/382/oj

        test_dict6 = {
            "bg": "Решение за изпълнение (ЕС) 2022/382 на Съвета от 4 март 2022 година за установяване на наличието на масов приток на разселени лица от Украйна по смисъла на член 5 от Директива 2001/55/ЕО и за въвеждане на временна закрила (текст от значение за ЕИП)",
            "cs": "Prováděcí rozhodnutí Rady (EU) 2022/382 ze dne 4. března 2022, kterým se stanoví existence masového přílivu vysídlených osob z Ukrajiny ve smyslu článku 5 směrnice 2001/55/ES a kterým se zavádí dočasná ochrana (Text s významem pro EHP)",
            "da": "Rådets gennemførelsesafgørelse (EU) 2022/382 af 4. marts 2022 om konstatering af, at der foreligger en massetilstrømning af fordrevne personer fra Ukraine som omhandlet i artikel 5 i direktiv 2001/55/EF, og om indførelse af midlertidig beskyttelse (EØS-relevant tekst)",
            "de": "Durchführungsbeschluss (EU) 2022/382 des Rates vom 4. März 2022 zur Feststellung des Vorliegens eines Massenzustroms von Vertriebenen aus der Ukraine im Sinne des Artikels 5 der Richtlinie 2001/55/EG und zur Einführung eines vorübergehenden Schutzes (Text von Bedeutung für den EWR)",
            "el": "Εκτελεστική απόφαση (ΕΕ) 2022/382 του Συμβουλίου, της 4ης Μαρτίου 2022, για τη διαπίστωση της ύπαρξης μαζικής εισροής εκτοπισθέντων ατόμων από την Ουκρανία κατά την έννοια του άρθρου 5 της οδηγίας 2001/55/ΕΚ και για την εισαγωγή προσωρινής προστασίας (Κείμενο που παρουσιάζει ενδιαφέρον για τον ΕΟΧ)",
            "en": "Council Implementing Decision (EU) 2022/382 of 4 March 2022 establishing the existence of a mass influx of displaced persons from Ukraine within the meaning of Article 5 of Directive 2001/55/EC, and having the effect of introducing temporary protection (Text with EEA relevance)",
            "es": "Decisión de Ejecución (UE) 2022/382 del Consejo de 4 de marzo de 2022 por la que se establece la existencia de una afluencia masiva de personas desplazadas procedentes de Ucrania en el sentido del artículo 5 de la Directiva 2001/55/CE y se introduce una protección temporal (Texto pertinente a efectos del EEE)",
            "et": "Nõukogu rakendusotsus (EL) 2022/382, 4. märts 2022, millega kehtestatakse Ukraina päritolu ümberasustatud isikute massilise sissevoolu olemasolu direktiivi 2001/55/EÜ artikli 5 tähenduses ja kehtestatakse ajutine kaitse (EMPs kohaldatav tekst)",
            "fi": "Neuvoston täytäntöönpanopäätös (EU) 2022/382, annettu 4 päivänä maaliskuuta 2022, Ukrainan kansalaisten joukkopaon olemassaolon toteamisesta direktiivin 2001/55/EY 5 artiklan mukaisesti ja tilapäisen suojelun käyttöönotosta (ETA:n kannalta merkityksellinen teksti)",
            "fr": "Décision d'exécution (UE) 2022/382 du Conseil du 4 mars 2022 établissant l'existence d'un afflux massif de personnes déplacées en provenance d'Ukraine au sens de l'article 5 de la directive 2001/55/CE et ayant pour effet d'introduire une protection temporaire (Texte présentant de l'intérêt pour l'EEE)",
            "ga": "Cinneadh Cur Chun Feidhme (AE) 2022/382 ón gComhairle an 4 Márta 2022 lena mbunaítear go bhfuil ollionradh daoine díláithrithe ón Úcráin ann de réir bhrí Airteagal 5 de Threoir 2001/55/CE agus lena mbunaítear cosaint shealadach (Téacs atá ábhartha maidir leis an LEE)",
            "hr": "Provedbena odluka Vijeća (EU) 2022/382 od 4. ožujka 2022. o utvrđivanju postojanja masovnog priljeva raseljenih osoba iz Ukrajine u smislu članka 5. Direktive 2001/55/EZ i uvođenju privremene zaštite (Tekst značajan za EGP)",
            "hu": "A Tanács (EU) 2022/382 végrehajtási határozata (2022. március 4.) az Ukrajnából érkező menekültek tömeges beáramlásának megállapításáról az 55/2001/EK irányelv 5. cikke értelmében, és az ideiglenes védelem bevezetéséről (EGT-vonatkozású szöveg)",
            "it": "Decisione di esecuzione (UE) 2022/382 del Consiglio del 4 marzo 2022 che accerta l'esistenza di un afflusso massiccio di sfollati dall'Ucraina ai sensi dell'articolo 5 della direttiva 2001/55/CE e introduce una protezione temporanea (Testo rilevante ai fini del SEE)",
            "lt": "2022 m. kovo 4 d. Tarybos įgyvendinimo sprendimas (ES) 2022/382, kuriuo nustatomas masinis iš Ukrainos perkeltų asmenų antplūdis, kaip apibrėžta Direktyvos 2001/55/EB 5 straipsnyje, ir įvedama laikinoji apsauga (Tekstas svarbus EEE)",
            "lv": "Padomes Īstenošanas lēmums (ES) 2022/382 (2022. gada 4. marts), ar ko nosaka, ka ir notikusi masveida pārvietoto personu pieplūde no Ukrainas Direktīvas 2001/55/EK 5. panta izpratnē, un ievieš pagaidu aizsardzību (Dokuments attiecas uz EEZ)",
            "mt": "Deċiżjoni ta' Implimentazzjoni tal-Kunsill (UE) 2022/382 tal-4 ta' Marzu 2022 li tistabbilixxi l-eżistenza ta' influss massiv ta' persuni spostati mill-Ukrajna fis-sens tal-Artikolu 5 tad-Direttiva 2001/55/KE u li għandha l-effett li tintroduċi protezzjoni temporanja (Test b'rilevanza għaż-ŻEE)",
            "nl": "Uitvoeringsbesluit (EU) 2022/382 van de Raad van 4 maart 2022 tot vaststelling van het bestaan van een massale toestroom van ontheemden uit Oekraïne in de zin van artikel 5 van Richtlijn 2001/55/EG en tot invoering van tijdelijke bescherming (Tekst met EER-relevantie)",
            "pl": "Decyzja wykonawcza Rady (UE) 2022/382 z dnia 4 marca 2022 r. stwierdzająca istnienie masowego napływu osób przemieszczonych z Ukrainy w rozumieniu art. 5 dyrektywy 2001/55/WE i wprowadzająca tymczasową ochronę (Tekst mający znaczenie dla EOG)",
            "pt": "Decisão de Execução (UE) 2022/382 do Conselho de 4 de março de 2022 que estabelece a existência de um afluxo maciço de pessoas deslocadas da Ucrânia na aceção do artigo 5.º da Diretiva 2001/55/CE e introduz uma proteção temporária (Texto relevante para o EEE)",
            "ro": "Decizia de punere în aplicare (UE) 2022/382 a Consiliului din 4 martie 2022 de stabilire a existenței unui aflux masiv de persoane strămutate din Ucraina în sensul articolului 5 din Directiva 2001/55/CE și de introducere a protecției temporare (Text cu relevanță pentru SEE)",
            "sk": "Vykonávacie rozhodnutie Rady (EÚ) 2022/382 z 4. marca 2022, ktorým sa ustanovuje existencia masového prílevu vysídlených osôb z Ukrajiny v zmysle článku 5 smernice 2001/55/ES a ktorým sa zavádza dočasná ochrana (Text s významom pre EHP)",
            "sl": "Izvedbeni sklep Sveta (EU) 2022/382 z dne 4. marca 2022 o ugotovitvi obstoja množičnega prihoda razseljenih oseb iz Ukrajine v smislu člena 5 Direktive 2001/55/ES in uvedbi začasne zaščite (Besedilo velja za EGP)",
            "sv": "Rådets genomförandebeslut (EU) 2022/382 av den 4 mars 2022 om fastställande av förekomsten av en massinströmning av fördrivna personer från Ukraina i den mening som avses i artikel 5 i direktiv 2001/55/EG och om införande av tillfälligt skydd (Text av betydelse för EES)"
        }
        for lang, title in test_dict6.items():
            title = Title(language=lang, value=title, celex_id="")
            print(f"{lang}: {title.shortname_without_institution}")
            assert title.shortname_without_institution != ""
            assert title.shortname_with_institution != ""
